server:
  port: 8081  # Usar puerto diferente a Keycloak

spring:
  datasource:
    url: jdbc:oracle:thin:@tlz3t5ba8btq7pbd_high?TNS_ADMIN=src/main/resources/wallet_tlz3t5ba8btq7pbd
    username: ADMIN2
    password: Admin1234567
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none  # Usa 'none' para no modificar el esquema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: temp@gmail.com
    password: temppassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloud:
    discovery:
      enabled: false  # Desactivar Eureka discovery temporalmente

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

jwt:
  secret: tu_clave_secreta_super_segura_aqui_2024_salon_booking_system
  expiration: 86400000  # 24 horas
